# Variable 'ENV' was defined in the Variables tab
# Variable 'SUB' was defined in the Variables tab
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Hosted VS2017
  steps:
  - checkout: self
  - task: AzureCLI@2
    displayName: Azure CLI resourcegroups/create-resourcegroups.sh
    inputs:
      connectedServiceNameARM: <connection>
      scriptType: bash
      scriptPath: resourcegroups/create-resourcegroups.sh
      cwd: resourcegroups
...
